name: iDisguise
main: de.luisagrether.idisguise.iDisguise
version: ${project.version}
api-version: 1.13
author: LuisaGrether
description: Disguise as a mob or other player.
website: https://www.spigotmc.org/resources/idisguise.5509/
loadbefore: [MinecraftTrainSimulator]
commands:
   disguise:
      description: Disguise yourself as a mob or other player.
      aliases: [d]
   odisguise:
      description: Disguise another player as a mob or other player.
      aliases: [od]
   undisguise:
      description: Undisguise yourself or another player.
      aliases: [ud]
